version: "3"
services:
  notes:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD: 'local'
    image: notes:1.1
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      #DEBUG: 'true'
      #SECURITY_SALT: 49e558df8e733a6daedbe054a9ccd7add9d9a6efa8a96cf3248815c364b47391
      DATABASE_URL: ${DB_CONNECTION}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}/${DB_DATABASE}
    networks:
      testing_net:
        ipv4_address: 183.83.1.1

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 9906:3306
    networks:
      testing_net:
        ipv4_address: 183.83.1.2
volumes:
  db_data: {}
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 183.83.0.0/16